import React, { useState, useEffect } from 'react';
import { Header } from './components/Header';
import { RepoInputHero } from './components/RepoInputHero';
import { LoadingSteppedProgress } from './components/LoadingSteppedProgress';
import { TabNavigation } from './components/TabNavigation';
import type { TabKey } from './components/TabNavigation';
import { OverviewCard } from './components/OverviewCard';
import { ArchitectureDiagram } from './components/ArchitectureDiagram';
import { ImportantFilesTable } from './components/ImportantFilesTable';
import { CodeFlowView } from './components/CodeFlowView';
import { ContributorGuideCard } from './components/ContributorGuideCard';
import { PotentialIssuesList } from './components/PotentialIssuesList';
import { ErrorAlert } from './components/ErrorAlert';

import { analyzeRepository, checkBackendHealth } from './services/api';
import type { AnalyzeResponse, HealthResponse } from './types';
import { Copy, Check } from 'lucide-react';

export const App: React.FC = () => {
  const [currentRepoUrl, setCurrentRepoUrl] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<AnalyzeResponse | null>(null);
  const [activeTab, setActiveTab] = useState<TabKey>('overview');
  const [health, setHealth] = useState<HealthResponse | null>(null);
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);

  useEffect(() => {
    // Check backend health on mount
    checkBackendHealth()
      .then(res => setHealth(res))
      .catch(() => {
        // Backend not yet reachable; normal if started in separate order
      });
  }, []);

  const handleAnalyze = async (url: string) => {
    setCurrentRepoUrl(url);
    setIsLoading(true);
    setError(null);
    setData(null);

    try {
      const response = await analyzeRepository(url);
      setData(response);
      setActiveTab('overview');
    } catch (err: any) {
      setError(err.message || 'An error occurred while analyzing the repository.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleReset = () => {
    setData(null);
    setError(null);
    setIsLoading(false);
  };

  const handleExportMarkdown = () => {
    if (!data) return;
    const { repository, analysis } = data;

    const md = `# RepoPilot AI Guide: ${repository.full_name}

> Generated by RepoPilot AI using ${repository.ai_model} (${repository.ai_provider})
> Repository: ${repository.html_url}

---

## 1. Project Overview
- **Name:** ${analysis.project_overview.name}
- **Description:** ${analysis.project_overview.description}
- **Technologies:** ${analysis.project_overview.technologies.join(', ')}
- **Stars:** ${repository.stars} | **Forks:** ${repository.forks} | **License:** ${repository.license || 'N/A'}

---

## 2. Architecture
${analysis.architecture.summary}

### Components:
${analysis.architecture.components.map(c => `- **${c.name}** (${c.type}): ${c.description}${c.connects_to.length ? ` -> connects to: ${c.connects_to.join(', ')}` : ''}`).join('\n')}

---

## 3. Code Flow
${analysis.code_flow}

---

## 4. Important Files
${analysis.important_files.map(f => `### \`${f.path}\`\n- **Purpose:** ${f.purpose}\n- **Why It Matters:** ${f.importance}`).join('\n\n')}

---

## 5. Contributor Starting Point ("Where Should I Start?")
- **Recommended File/Folder:** \`${analysis.contributor_guide.starting_point}\`
- **Why Start Here:** ${analysis.contributor_guide.reason}
- **Suggested First Contribution:** ${analysis.contributor_guide.suggested_contribution}

---

## 6. Potential Issues (Needs Human Review)
${analysis.potential_issues.map(iss => `### [${iss.confidence.toUpperCase()}] ${iss.file}\n- **Description:** ${iss.description}\n- **Evidence/Reason:** ${iss.reason}`).join('\n\n')}
`;

    navigator.clipboard.writeText(md);
    setCopiedMarkdown(true);
    setTimeout(() => setCopiedMarkdown(false), 2500);
  };

  return (
    <div className="min-h-screen bg-[#0b0f19] text-slate-100 flex flex-col font-sans selection:bg-cyan-500/30 selection:text-cyan-200">
      {/* Top Header */}
      <Header
        repository={data?.repository}
        onReset={handleReset}
        aiProvider={health?.ai_provider || data?.repository.ai_provider}
        aiModel={health?.ai_model || data?.repository.ai_model}
      />

      {/* Main Content Area */}
      <main className="flex-1">
        {!data && !isLoading && !error && (
          <RepoInputHero
            onAnalyze={handleAnalyze}
            isLoading={isLoading}
            aiProviderName={health?.ai_provider}
            aiModelName={health?.ai_model}
          />
        )}

        {isLoading && (
          <LoadingSteppedProgress repoUrl={currentRepoUrl} />
        )}

        {error && (
          <ErrorAlert
            message={error}
            onRetry={() => handleAnalyze(currentRepoUrl)}
            onReset={handleReset}
          />
        )}

        {data && !isLoading && (
          <div className="animate-in fade-in duration-500">
            {/* Dashboard Sub-Header with Export Button */}
            <div className="bg-slate-950/60 border-b border-slate-800 py-3 px-4 sm:px-6 lg:px-8">
              <div className="max-w-7xl mx-auto flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div className="flex items-center gap-2 text-xs font-mono text-slate-400">
                  <span className="w-2 h-2 rounded-full bg-emerald-400" />
                  <span>Analysis Ready for:</span>
                  <span className="text-white font-semibold">{data.repository.full_name}</span>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={handleExportMarkdown}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-700 text-xs font-mono text-cyan-300 transition-colors cursor-pointer"
                    title="Copy complete developer guide as Markdown"
                  >
                    {copiedMarkdown ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-400" />
                        <span className="text-emerald-400">Copied to Clipboard!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Copy Developer Guide (MD)</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>

            {/* Tab Navigation */}
            <TabNavigation
              activeTab={activeTab}
              onTabChange={setActiveTab}
              filesCount={data.analysis.important_files.length}
              issuesCount={data.analysis.potential_issues.length}
            />

            {/* Tab Contents */}
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
              {activeTab === 'overview' && (
                <OverviewCard
                  overview={data.analysis.project_overview}
                  repository={data.repository}
                />
              )}

              {activeTab === 'architecture' && (
                <ArchitectureDiagram
                  architecture={data.analysis.architecture}
                />
              )}

              {activeTab === 'files' && (
                <ImportantFilesTable
                  files={data.analysis.important_files}
                  repository={data.repository}
                />
              )}

              {activeTab === 'flow' && (
                <CodeFlowView
                  codeFlow={data.analysis.code_flow}
                />
              )}

              {activeTab === 'contribute' && (
                <ContributorGuideCard
                  guide={data.analysis.contributor_guide}
                  repository={data.repository}
                />
              )}

              {activeTab === 'issues' && (
                <PotentialIssuesList
                  issues={data.analysis.potential_issues}
                />
              )}
            </div>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-800/80 bg-slate-950 py-6 text-center text-xs text-slate-500 font-mono">
        <div className="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <span className="font-semibold text-slate-400">RepoPilot AI</span>
            <span>—</span>
            <span>Open-Weight Repository Understanding & Contributor Engine</span>
          </div>
          <div>
            <span>MIT License • Hacktoberfest 2026</span>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default App;
